name 'meeh-java'
version '0.1.1'
source 'git://github.com/meeh420/puppet-java.git'
author 'Mikal Villa'
license 'BSD'
summary 'Oracle and/or OpenJDK Java Puppet Module'
description 'This module manages Oracle and/or OpenJDK Java installations. Tested on Ubuntu(precise) and Debian(Wheezly/unstable)'
project_page 'http://github.com/meeh420/puppet-java'
dependency 'puppetlabs/apt', '>= 1.0.1'
